version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 antivirus_api.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
      - redis

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672" # RabbitMQ management UI
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: "redis:alpine"

  celery:
    build: .
    command: celery -A antivirus_api worker --loglevel=info --pool=solo
    volumes:
      - .:/app
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started

  frontend:
    build:
      context: .
      dockerfile: antivirus-frontend/Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - web
